from pyaslreport.modalities import asl, testdsc
from .modalities.registry import get_processor
from pyaslreport.sequences.factory import get_sequence
import pydicom
from pydicom.errors import InvalidDicomError
import os
import logging as log

def generate_report(data):
    """
    Generates a report based on the provided data for a specific modality.
    The modality is determined from the 'modality' key in the data dictionary.
    :param data: Dictionary containing modality data, including the 'modality' key.
    :return: Report generated by the processor for the specified modality.
    """
    modality = data.get("modality")  # e.g., "asl", "dsc" and so on
    processor_class = get_processor(modality)
    processor = processor_class(data)

    return processor.process()


def get_bids_metadata(data):
    """
    Converts the provided data to BIDS format.
    :param data: Dictionary containing modality data.
    :return: BIDS-formatted data.
    """
    modality = data.get("modality")
    dicom_dir = data.get("dicom_dir")
    dicom_header = get_dicom_header(dicom_dir)
    sequence = get_sequence(modality, dicom_header)
    
    if sequence is None:
        raise ValueError(f"No matching sequence found for modality '{modality}' with the provided DICOM header")
    
    return sequence.extract_bids_metadata()


def get_dicom_header(dicom_dir: str):
    """
    Extracts the DICOM header from the provided DICOM files.
    :param dicom_dir: Directory containing DICOM files.
    :return: DICOM header from the first valid DICOM file found.
    """
    # Get all files in the directory
    all_files = [f for f in os.listdir(dicom_dir) if os.path.isfile(os.path.join(dicom_dir, f))]
    
    # Return the first readable DICOM header instead of scanning the whole directory
    # and reading the winning file a second time.
    for file in all_files:
        file_path = os.path.join(dicom_dir, file)
        try:
            dcm_header = pydicom.dcmread(file_path, stop_before_pixels=True)
            log.info(f"Found a readable DICOM file in {dicom_dir}: {file}")
            return dcm_header
        except (InvalidDicomError, OSError, PermissionError):
            # File is not a valid DICOM file or cannot be read
            continue

    raise ValueError(f"No DICOM files found in directory: {dicom_dir}")